### ISSUE TITLE
Responsive breakpoint switcher 

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2-page-builder#636]
As a Marketer I want to switch between supported viewports and see the content preview with corresponding styles applied
#### Acceptance Criteria:
1. User opens content with PageBuilder and sees the desktop breakpoint selected. Content is displayed with desktop styles applied
1. User switches the breakpoint to mobile view and sees the content updated with the mobile styles applied (columns layout, images, banner, slider and product carousel layout )
1. User opens any content type configuration, makes changes and sees that changes applied across all the breakpoints
1. User can't make changes to the columns width when on a viewport other than desktop
1. User saves content and sees the changes on storefront on each of the breakpoint

Design: <https://xd.adobe.com/view/22bceb98-7058-4a1a-9803-47499d472681-77ef/]
  
#### Sub-tasks:
 - [x] Prototype - [https://github.com/magento/magento2-page-builder/tree/viewport-switcher]
 - [x] Add icons to the viewport switcher buttons. @yolouiese
 - [x] Add tooltip with viewport label and description. @joweecaquicla
 - [x] Move frontend mobiles specific styles to the admin area. @yolouiese
 - [x] Fix tests/stabilization. @joweecaquicla
 - [x] Create functional tests @joweecaquicla

Bugs:
1. Fix snapshot resizing when exiting fullscreen mode.(Fixed in [https://github.com/magento/magento2-page-builder/pull/664])

#### Manual checks for ticket
* [x] Verify viewport icons & tooltips match UX design (selected & unselected)
* [x] Verify viewport in Desktop mode looks like normal Page Builder stage (same as before changes)
* [x] Verify viewport in Mobile mode looks like like UX mockup (smaller viewport, gray areas on sides
* [x] Verify that content rendered in Mobile viewport in admin matches the same content when rendered in the same size mobile viewport on storefront
  * [x] Row
    * [ ] Check each unique appearance
    * [ ] Each unique attribute value (parallax, Image & video background, mobile background image, min height, etc)
    * [ ] Check can edit, duplicate, move, delete content type from on hover menu
  * [x] Column
    * [ ] Check each unique appearance
    * [ ] Each unique attribute value (Image background, mobile background image, min height, etc)
    * [ ] Verify that columns stack in mobile viewport & disregard column size in desktop mode
    * [ ] Cannot resize columns or edit column grid size
    * [ ] Check can edit, duplicate, move, delete content type from on hover menu
  * [x] Tabs/Tab Item
    * [ ] Each unique attribute value (tab header positioning, default tabs, background, min height, etc.)
    * [ ] Check w/ multiple tabs
    * [ ] Check inline editing tab names
    * [ ] Check can edit, duplicate, move, add, delete content type from on-hover menu (tabs)
    * [ ] Check can edit, duplicate, move, delete content type from on-click menu (tab item)
  * [x] Heading
    * [ ] Each unique attribute value
    * [ ] Check inline editing
      * [ ] Check inline edit toolbar does not have z-index issues where it gets hidden by viewport dead space or other content types or pagebuilder header
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
  * [x] Text
    * [ ] Each unique attribute value
    * [ ] Check inline editing
      * [ ] Check inline edit toolbar does not have z-index issues where it gets hidden by viewport dead space or other content types or pagebuilder header
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
  * [x] Buttons/Button Item
    * [ ] Each unique attribute value
    * [ ] Check inline editing
    * [ ] Check can edit, duplicate, move, add , delete content type from on-hover menu (buttons)
    * [ ] Check can edit, duplicate, move, delete content type from on-click menu (button item)
  * [x] Divider
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
  * [x] HTML Code
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Verify html is always shown as plaintext & does not render
  * [x] Image
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Check can upload image from stage using upload button, select from gallery button, or dragging & dropping image from local machine (upload area should initialize)
  * [x] Banner
    * [ ] Check each unique appearance
    * [ ] Each unique attribute value
    * [ ] Check inline editing content
      * [ ] Check inline edit toolbar does not have z-index issues where it gets hidden by viewport dead space or other content types or pagebuilder header
    * [ ] Check inline editing button item
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
  * [x] Slider
    * [ ] Check each unique appearance
    * [ ] Each unique attribute value
    * [ ] Check inline editing content
      * [ ] Check inline edit toolbar does not have z-index issues where it gets hidden by viewport dead space or other content types or pagebuilder header
    * [ ] Check inline editing button item
    * [ ] Check can edit, duplicate, move, add, delete content type from on-hover menu (slider)
    * [ ] Check can edit, duplicate, move, delete content type from on-click menu (slide item)
  * [x] Video
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
  * [x] Map
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Check can use map (move, zoom, open location pin, full screen, etc)
  * [x] Block
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Check rendering all other content types through block will render as expected
  * [x] Dynamic Block
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Check rendering all other content types through block will render as expected
  * [x] Products
    * [ ] Check each unique appearance
      * [ ] Check can move between products in product carousel
    * [ ] Each unique attribute value
    * [ ] Check can edit, duplicate, move, delete content type from on-hover menu
    * [ ] Check cannot interact with product items in admin
* [x] Verify editing content types in mobile viewport will also change value in desktop viewport
  * [ ] Verify vice-versa

#### Integration Tests

None
#### Automated MFTF Tests
 - [x] Create functional tests.
  1. ### [ ] Copy the following test cases to create new test cases that test the rendering of content in admin & on storefront in a mobile viewport @joweecaquicla . name similar to `ViewportSwitcherMobileContainedRowThroughBlockContentTypeTest` for each below copied test. filename should be same as test name. put all new tests in new directory under `Test`: `ViewportSwitcherMobile`. for `[stories]` annotation, use `Viewport Switcher` as value. `severity` for all below should be `CRITICAL`
      1. ##### [ ] BlockRenderContainedRowMinHeightThroughBlockContentTypeTest
        1. [ ] BlockRenderFullWidthRowMinHeightThroughBlockContentTypeTest
        1. [ ] BlockRenderFullBleedRowMinHeightThroughBlockContentTypeTest
        1. [ ] BlockRenderColumnFullHeightAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderColumnTopAlignmentAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderColumnCenterAlignmentAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderColumnBottomAlignmentAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderTabsThroughBlockContentTypeTest
        1. [ ] BlockRenderButtonsThroughBlockContentTypeInlineSameSizeTest
        1. [ ] BlockRenderButtonsThroughBlockContentTypeStackedNotSameSizeTest
        1. [ ] BlockRenderDividerThroughBlockContentTypeTest
        1. [ ] BlockRenderHeadingThroughBlockContentTypeTest
        1. [ ] BlockRenderHTMLThroughBlockContentTypeTest
        1. [ ] BlockRenderTextThroughBlockContentTypeTinyMCE4WysiwygEnabledByDefaultTest
        1. [ ] BlockRenderImageThroughBlockContentTypeTest
        1. [ ] BlockRenderVideoThroughBlockContentTypeTest
        1. [ ] BlockRenderSlideItemPosterAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderSlideItemCollageLeftAppearanceWithVideoBackgroundThroughBlockContentType
        1. [ ] BlockRenderSlideItemCollageCenterAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderSlideItemCollageRightAppearanceWithVideoBackgroundThroughBlockContentType
        1. [ ] BlockRenderBannerPosterAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderBannerCollageLeftAppearanceWithVideoBackgroundThroughBlockContentTypeTest
        1. [ ] BlockRenderBannerCollageCenteredAppearanceThroughBlockContentTypeTest
        1. [ ] BlockRenderBannerCollageRightAppearanceWithVideoBackgroundThroughBlockContentTypeTest
        1. [ ] BlockRenderBlockThroughBlockContentTypeTest
        1. [ ] BlockRenderProductsThroughBlockContentTypeTest
        1. [ ] BlockRenderDefaultProductsCarouselThroughBlockContentTypeTest
        1. [ ] BlockRenderProductsCarouselVerifyProductItemsInteractionsOnStorefrontInDefaultCarouselModeTest
        1. [ ] PageBuilderBlockRenderDynamicBlockThroughBlockContentTypeTest
    1. [x] Copy the following test cases to create new test cases that verify user can use content types in new viewport in admin. name similar to `ViewportSwitcherMobileAddChildContentTypesFromOnHoverOptionMenusTest` for each below copied test. filename should be same as test name. put all new tests in same new directory above: `ViewportSwitcherMobile`. for `[stories]` annotation, use `Viewport Switcher` as value. `severity` for all below should be `CRITICAL` @yolouiese
      1. ##### [ ] PageBuilderCatalogProductVerifyCanAddChildContentTypesFromOnHoverOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanDeleteContentTypesFromOnClickOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanDeleteContentTypesFromOnHoverOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanDuplicateContentTypesFromOnClickOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanDuplicateContentTypesFromOnHoverOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanEditContentTypesFromOnClickOptionMenusTest
        1. [ ] PageBuilderCatalogProductVerifyCanEditContentTypesFromOnHoverOptionMenusTest
        1. [ ] PageBuilderCatalogCategoryVerifyCanMoveButtonItemsTest
        1. [ ] PageBuilderCatalogProductVerifyCanMoveContentTypesFromOnHoverOptionMenusTest
        1. [ ] PageBuilderCatalogCategoryVerifyCanMoveSlideItemsTest
        1. [ ] PageBuilderCatalogCategoryVerifyCanMoveTabItemsTest
        1. [ ] HeadingEditTypeH1StageTest
        1. [ ] ButtonItemCanBeEditedInlineTest
        1. [ ] EditTabNameByClickingOnHeaderInStageTest
        1. [ ] BannerUploadImageFromStageTest (but write test for Image content type)
        1. [ ] BannerUploadImageFromStageTest
        1. [ ] SlideItemUploadImageFromStageTest
    1. [x] New test to verify each new viewport icon & each new tooltip text. Also verify viewport area of desktop & mobile @joweecaquicla.
      * name: `AdminVerifyViewportSwitcherUITest`. filename should be same as test name. put new test in same new directory above: `ViewportSwitcherMobile`.
      * for `[stories]` annotation, use `Viewport Switcher` as value
      * `severity` should be `MAJOR`
    1. [x] New test to verify cannot resize columns & columns wrap @joweecaquicla
      * name: `AdminViewportSwitcherMobileVerifyCannotResizeColumnsTest`. filename should be same as test name. put new test in same new directory above: `ViewportSwitcherMobile`.
      * for `[stories]` annotation, use `Viewport Switcher` as value
      * `severity` should be `MAJOR`

#### Manual Hip Tests

None
#### Manual Zephyr Tests
* [ ] Update manual test cases to include switching to mobile viewport in admin, set unique content type configuration, and verify on storefront
  * [ ] general smoke test - https://jira.corp.magento.com/browse/MC-32435
  * [ ] row - https://jira.corp.magento.com/browse/MC-32475
  * [ ] columns - https://jira.corp.magento.com/browse/MC-4951
  * [ ] tabs - https://jira.corp.magento.com/browse/MC-4326
  * [ ] text - https://jira.corp.magento.com/browse/MC-4235
  * [ ] buttons - https://jira.corp.magento.com/browse/MC-4952
  * [ ] divider - https://jira.corp.magento.com/browse/MC-4325
  * [ ] html code - https://jira.corp.magento.com/browse/MC-4953
  * [ ] heading - https://jira.corp.magento.com/browse/MC-4246
  * [ ] image - https://jira.corp.magento.com/browse/MC-4954
  * [ ] banner - https://jira.corp.magento.com/browse/MC-32474
  * [ ] slider - https://jira.corp.magento.com/browse/MC-32473
  * [ ] video - https://jira.corp.magento.com/browse/MC-32472
  * [ ] map - https://jira.corp.magento.com/browse/MC-4963
  * [ ] block - https://jira.corp.magento.com/browse/MC-4964
  * [ ] dynamic block - https://jira.corp.magento.com/browse/MC-4966
  * [ ] products - https://jira.corp.magento.com/browse/MC-23047
  * [ ] inline edit - https://jira.corp.magento.com/browse/MC-4315
  * [ > parallax - https://jira.corp.magento.com/browse/MC-5223

 

 
## Note:

In the UI, the tooltip should state more precisely what is the breakpoint rule is: "Minimum width: 768px" instead of "Width" 768px"
