### ISSUE TITLE
Form field/field group viewport scope

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2-page-builder#637]
As a Marketer I want to see the scope of viewports that content type settings applied to **so that** I know to which viewport the settings are applied 

## Precondition
1. User edits content with Page Builder 
2. User edits desktop (global) viewport 
2. User opened the configuration of the content type that has "min height" (Row, Column, Tab, Banner, Slide, Slider)

## Acceptance Criteria
1. User sees all form fields to have a desktop scope (no icon)
2. User updates the min height value and saves the configuration 
3. User views page content on the storefront and sees the min height value applied to correct scope (both desktop and mobile)
4. User goes back to editing, switches to the mobile breakpoint and opens a given content type configuration 
5. User sees the Min height field scope to be updated to mobile (icon is there) and the value is same that was previously set for the desktop. User sees a tooltip with the explanation of the field scope on hover.
6. User updated the min height value for the mobile breakpoint and saves the configuration 
7. User views page content on the storefront and sees the min height value applied to correct scope (desktop and mobile have different values)
8. User goes back to editing, switches to the mobile breakpoint and changes the min height value to either none or same value that is on desktop
9. User goes to the storefront and sees that min height value is global (one value for all breakpoints)

## Sub-tasks
- [x] Provide prototype - https://github.com/magento/magento2-page-builder/tree/637-form-field-viewport-scope - @omiroshnichenko
- [x] Add mobile icon and tooltip for min-height field
- [x] Apply changes to content types:
    - [ ] Banner
    - [x] Tabs
    - [ ] Tab Item
    - [ ] Column
    - [ ] Row
    - [ ] Slide
    - [ ] Slider
- [ ] Fix tests/stabilization
- [x] Create functional tests

---

#### Primary Checks For Each Content Type
- [x] Perform below steps for each of the following content types & appearances
  - [x] Row
    - [ ] Contained
    - [ ] Full Width
    - [ ] Full Bleed
  - [x] Column
    - [ ] Full Height
    - [ ] Top Aligned
    - [ ] Center Aligned
    - [ ] Bottom Aligned
  - [x] Tab Group
  - [ ] Tab Item
  - [ ] Banner
    - [ ] Poster
    - [ ] Collage Left
    - [ ] Collage Centered
    - [ ] Collage Right
  - [ ] Slider
  - [ ] Slide Item
    - [ ] Poster
    - [ ] Collage Left
    - [ ] Collage Centered
    - [ ] Collage Right
- [x] **Scenario**: Add new content type on CMS Block stage, edit nothing in either viewport, & save
  - [ ] Verify content type edit panel on desktop viewport is default value
  - [ ] Verify content type edit panel on mobile viewport is default value
  - [ ] Verify content type in admin cms block stage renders with default value min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with default value min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with default value min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with default value min height on mobile viewport
  - [ ] Verify content type on storefront renders with default value min height on desktop viewport
  - [ ] Verify content type on storefront renders with default value min height on mobile viewport
- [x] **Scenario**: Add new content type on CMS Block stage, change content type's min height value on desktop viewport to 500px, don't edit mobile viewport, & save
  - [ ] Verify content type edit panel on desktop viewport is 500px
  - [ ] Verify content type edit panel on mobile viewport is 500px
  - [ ] Verify content type in admin cms block stage renders with 500px min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with 500px min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with 500px min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with 500px min height on mobile viewport
  - [ ] Verify content type on storefront renders with 500px min height on desktop viewport
  - [ ] Verify content type on storefront renders with 500px min height on mobile viewport
- [x] **Scenario**: Add new content type on CMS Block stage, don't edit desktop viewport, change content type's min height value on mobile viewport to 400px & save
  - [ ] Verify content type edit panel on desktop viewport is set to default value
  - [ ] Verify content type edit panel on desktop viewport is set to 400px
  - [ ] Verify content type in admin cms block stage renders with default min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with 400px min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with default min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with 400px min height on mobile viewport
  - [ ] Verify content type on storefront renders with default min height on desktop viewport
  - [ ] Verify content type on storefront renders with 400px min height on mobile viewport
- [x] **Scenario**: Add new content type on CMS Block stage, change content type's min height value on mobile viewport to 400px, save, change content type's min height value on desktop viewport to 500px & save
  - [ ] Verify content type edit panel on desktop viewport is 500px
  - [ ] Verify content type edit panel on mobile viewport is 400px
  - [ ] Verify content type in admin cms block stage renders with 500px min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with 400px min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with 500px min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with 400px min height on mobile viewport
  - [ ] Verify content type on storefront renders with 500px min height on desktop viewport
  - [ ] Verify content type on storefront renders with 400px min height on mobile viewport
- [x] **Scenario**: Add new content type on CMS Block stage, change content type's min height value on mobile viewport to empty, save, change content type's min height value on desktop viewport to 500px & save
  - [ ] Verify content type edit panel on desktop viewport is 500px
  - [ ] Verify content type edit panel on mobile viewport is empty
  - [ ] Verify content type in admin cms block stage renders with 500px min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with 500px min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with 500px min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with 500px min height on mobile viewport
  - [ ] Verify content type on storefront renders with 500px min height on desktop viewport
  - [ ] Verify content type on storefront renders with 500px min height on mobile viewport
- [x] **Scenario**: Add new content type on CMS Block stage, change content type's min height value on desktop viewport to empty, save, change content type's min height value on mobile viewport to 500px & save
  - [ ] Verify content type edit panel on desktop viewport is empty
  - [ ] Verify content type edit panel on mobile viewport is 500px
  - [ ] Verify content type in admin cms block stage renders with default min height on desktop viewport
  - [ ] Verify content type in admin cms block stage renders with 500px min height on mobile viewport
  - [ ] Add block to cms page &
    - [ ] Verify content type in admin cms page stage renders with empty min height on desktop viewport
    - [ ] Verify content type in admin cms page stage renders with 500px min height on mobile viewport
  - [ ] Verify content type on storefront renders with empty min height on desktop viewport
  - [ ] Verify content type on storefront renders with 500px min height on mobile viewport

#### Other Checks
- [ ] Verify that upgraded PageBuilder content is unaffected
  - Install Magento 2.4.1 on local
  - Create Page Builder content (1 of each content type & appearance)
    - Set some min heights explicitly, set some as defaults, set some as 0, set some to empty
  - Save page
  - Upgrade to latest 2.4-develop
  - Verify data is unchanged for each content type in both desktop & mobile viewports
- [ ] Verify mobile icon appears ONLY for min height field on each above content type
  - [ ] Row, Column, Tabs, Tab Item, Banner, Slider, Slide Item
  - [ ] Verify tooltip has correct message
  - [ ] Verify cursor is correct when hovering over tooltip
  - [ ] Verify tooltip on
    - [ ] Chrome
    - [ ] Safari
    - [ ] Edge
    - [ ] Firefox
  - [ ] Verify tooltip message is translatable

### Integration Tests
None

### Automated MFTF Tests
- [ ] Add new test. 1 for each content type. put in ViewportSwitcherMobile directory
  - name: (ex: ViewportSwitcherMobileRowMinHeightTest, ViewportSwitcherMobileBannerMinHeightTest)
  - features: PageBuilder
  - stories: Viewport Switcher
  - title: Mobile Viewport: (ex: Verify Row Minimum Height Works As Expected Between Mobile And Desktop)
  - description: (ex: Verify Row's minimum height behaves as expected when desktop is set & mobile is empty, when desktop is set and mobile is set to calculated value, and when desktop is empty and mobile is set. Verify on desktop and mobile viewports on CMS Block stage, CMS Page through Block, and storefront.)
  - severity: BLOCKER
  - groups: 
    - pagebuilder
    - pagebuilder-viewport-switcher
    - pagebuilder-cms-block
    - (ex: pagebuilder-row)
  - steps:
    - add content type to cms block stage
    - duplicate twice to have 3 total content types
    - edit 1st, set desktop to 500px, confirm no mobile icon/tooltip, edit mobile, confirm mobile icon/tooltip, confirm set to empty, dont change mobile
    - edit 2nd, set desktop to 500px, set mobile to calc(100vh - 200px)
      - when extending test for content types that do not support calculated min heights, set the mobile viewport to 200px
    - edit 3rd, set desktop to empty, set mobile to 200px
    - check rendering of all 3 on cms block stage desktop (assert calculated style & assert actual height)
    - check rendering of all 3 on cms block stage mobile (assert calculated style & assert actual height)
    - add block to page
    - check rendering of all 3 on cms page stage desktop (assert calculated style & assert actual height)
    - check rendering of all 3 on cms page stage mobile (assert calculated style & assert actual height)
    - save page
    - check rendering of all 3 on cms page storefront desktop (assert calculated style & assert actual height)
    - check rendering of all 3 on cms page storefront mobile (assert calculated style & assert actual height)
- [ ] Extend above for each content type
  - [ ] Row
  - [ ] Column
  - [ ] Tab Group
  - [ ] Tab Item
  - [ ] Banner
  - [ ] Slider
  - [ ] Slide Item

### Manual Hip Tests
None

### Manual Zephyr Tests
None
